server.port=9002
server.servlet.context-path=/codal
spring.application.name=codal-api
external.codal.base-url=https://search.codal.ir/api
springdoc.swagger-ui.path=/doc.html
logging.level.com.ernoxin=DEBUG
