server.port=9002
server.servlet.context-path=/codal
spring.application.name=codal-api
external.codal.base-url=https://search.codal.ir/api
external.codal.user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)
external.codal.referer=https://codal.ir/
external.codal.origin=https://codal.ir
springdoc.swagger-ui.path=/doc.html
logging.level.com.ernoxin=DEBUG
